parkg: PartialKeyGen.c
	gcc PartialKeyGen.c -o parkg
#example: test.c
#	gcc test.c -o test
# CXX := clang
# LLVMLDFLAGS := --target=wasm32 -nostdlib -Wl,--no-entry
# SOURCES = add.c
# OBJECTS = $(SOURCES:.c=.wasm32)
#
# adder: adder.c
#     $(CXX) $(LLVMLDFLAGS) -o $(SOURCES)
#adder: adder.c
# clang --target=wasm32 -nostdlib -Wl,--no-entry -o adder.wasm adder.c
# this file is still a fake. Pending to translate below to a correct makefile.